name: Build Invoice Merger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter tkinterdnd2 pillow pypdf2 pyinstaller
        
    - name: Install Ghostscript
      run: brew install ghostscript
        
    - name: List files (debug)
      run: ls -la
        
    - name: Build macOS app
      run: |
        pyinstaller --onefile --windowed --name Invoice_Merger_v1.4.2 invoice_flatten_merge.py
        mv "dist/Invoice_Merger_v1.4.2.app" "Invoice Merger.app"

    - name: Bundle Ghostscript with app
      run: |
        # Create ghostscript directory in app bundle  
        mkdir -p "Invoice Merger.app/Contents/Resources/ghostscript"
        # Copy Ghostscript binary to app bundle
        cp "$(brew --prefix ghostscript)/bin/gs" "Invoice Merger.app/Contents/Resources/ghostscript/"
        # Make it executable
        chmod +x "Invoice Merger.app/Contents/Resources/ghostscript/gs"
        # Verify it was copied
        ls -la "Invoice Merger.app/Contents/Resources/ghostscript/"

    - name: Create DMG
      run: |
        hdiutil create -volname "Invoice Merger" -srcfolder "Invoice Merger.app" -ov -format UDZO "Invoice_Merger_v1.4.2.dmg"
        
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: Invoice_Merger_v1.4.2.dmg
        
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: Invoice Merger.app