name: macOS build

on:
  push:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - run: pip install -r requirements.txt pyinstaller

      - name: Build .app
        run: pyinstaller -y --windowed --name InvoiceMerge invoice_flatten_merge.py

      - name: Install Ghostscript
        run: brew install ghostscript

      - name: Vendor Ghostscript
        run: |
          GS_PREFIX=$(brew --prefix ghostscript)
          mkdir -p dist/InvoiceMerge.app/Contents/Resources/ghostscript
          cp "$GS_PREFIX/bin/gs" dist/InvoiceMerge.app/Contents/Resources/ghostscript/
          cp -R "$GS_PREFIX/lib" "$GS_PREFIX/share/ghostscript" \
            dist/InvoiceMerge.app/Contents/Resources/ghostscript/

      # (Optional) Codesign & notarize steps here

      - name: Create DMG
        run: |
          hdiutil create -volname InvoiceMerge \
            -srcfolder dist/InvoiceMerge.app -ov -format UDZO InvoiceMerge.dmg

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          files: InvoiceMerge.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
